### ISSUE TITLE
Custom reject message

### ISSUE THREAD

**Issue by jduepmeier** [cmail-mta/cmail#1]
Have the parameter to a 'reject' router be the message printed in the RCPT TO response.

**Comment by cbdevnet** [comment]
This would involve adding an additional return parameter to path_resolve as called in https://github.com/cmail-mta/cmail/blob/master/cmail-smtpd/smtpstatemachine.c#L409.

Since the message text memory is owned by SQLite within path_resolve (see https://github.com/cmail-mta/cmail/blob/master/cmail-smtpd/path.c#L109), this would involve heap-copying and immediately freeing the message, which is pretty hacky.

**Comment by cbdevnet** [comment]
Another option would be to have route resolution occur within path_resolve (https://github.com/cmail-mta/cmail/blob/master/cmail-smtpd/path.c#L105), which it already partially does and store the route as member of the PATH structure. This would allow access to the route parameter from within the state machine, but would require more care when free'ing paths. It should probably also be considered a layering violation (Accessing route data from within path code).

**Comment by cbdevnet** [comment]
This was implemented in the (as of yet not release-ready) untangle-routers branch in commit a908945e07cb3ae797df01653f4dc78b97607360, which is soon to be merged into master.
