### ISSUE TITLE
Check database schema version

### ISSUE THREAD

**Issue by jduepmeier** [cmail-mta/cmail#4]
MSA should check the database schema version. When in logmode there is now error when database version is not the same (but you can get prepare statement compile errors). Prepared statement compile errors should also been reported in stderr when logfile is enabled.

**Comment by cbdevnet** [comment]
Rudimentary schema version checking now implemented in msa, popd and mta.
Currently only checks against "different than CMAIL_CURRENT_SCHEMA_VERSION"
Might also check upgrade paths or backwards compatability.

stderr logging with file logging enabled is problematic because daemonisation closes the stderr descriptor. Will create a new bug for that.
